### ISSUE TITLE
Posts - column sorting icon broken. Works when hovering

### ISSUE THREAD

**Issue by bluesix** [fatihbalsoy/material-board#16]
Posts page column sorting icons appear to be broken. Show correctly when hovering.
Oddly they work correctly on Pages

![image](https://github.com/fatihbalsoy/material-board/assets/195220/4b61cbb4-b4f9-43d6-866a-851db16997f2)

**Comment by fatihbalsoy** [comment]
Thanks for reporting this issue! It has been fixed and I will shortly push an update.
